# Work in progress
core:
    debug: false # WP_DEBUG
    debug_display: true # WP_DEBUG_DISPLAY
    debug_log: false # WP_DEBUG_LOG
    debug_scripts: false # WP_SCRIPT_DEBUG
    auto_update_core: false # WP_AUTO_UPDATE_CORE
    allow_multisite: false # WP_ALLOW_MULTISITE
    allow_repair: false # WP_ALLOW_REPAIR
    proxy:
        host: ~ # WP_PROXY_HOST
        port: ~ # WP_PROXY_PORT
        user: ~ # WP_PROXY_USERNAME
        pass: ~ # WP_PROXY_PASSWORD
        bypass_hosts: ~ # WP_PROXY_BYPASS_HOSTS
        block_external: false # WP_HTTP_BLOCK_EXTERNAL

    filesystem_method: ~
    directories:
        # languages: null # WP_LANG_DIR
        # plugins: ~ # WP_PLUGIN_DIR
    # plugin_url: ~ # WP_PLUGIN_URL

multisite:
    no_blog_redirect: ~ # NOBLOGREDIRECT
    subdomain_install: ~ # SUBDOMAIN_INSTALL
    directories:
        # plugins: null # WPMU_PLUGIN_DIR
    # plugin_url: ~ # WPMU_PLUGIN_URL
