services:
    database:
        class: Devtronic\FreshPress\Core\WPDB
        arguments: ['%database.user%', '%database.pass%', '%database.name%', '%database.host%']

    twig_loader:
        class: Devtronic\FreshPress\Core\Twig\Loader
        arguments: ['web/wp-content/themes/', '%core.install_path%']

    twig:
        class: Twig_Environment
        arguments: ['@twig_loader']