services:
    # app.my_service:
    #     class: FQCN\To\Service
    #     arguments: ['Some Arguments', '@service_container']
    database:
        class: Devtronic\FreshPress\Core\WPDB
        arguments: ['%database.user%', '%database.pass%', '%database.name%', '%database.host%']

    twig_loader:
        class: Twig_Loader_Filesystem
        arguments: ['wp-content/themes/', ~]

    twig:
        class: Twig_Environment
        arguments: ['@twig_loader']